"""empty message

Revision ID: 0a8c7ec878a5
Revises: 50cd474ac607
Create Date: 2020-08-21 13:29:43.599636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a8c7ec878a5'
down_revision = '50cd474ac607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('ddl', sa.String(length=63), nullable=True))
    op.drop_column('assignment', 'due')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('due', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('assignment', 'ddl')
    # ### end Alembic commands ###
