"""empty message

Revision ID: 413003d967c5
Revises: a51e41e314e0
Create Date: 2020-08-20 00:45:14.782442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413003d967c5'
down_revision = 'a51e41e314e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('filename', sa.String(length=63), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'filename')
    # ### end Alembic commands ###
