"""empty message

Revision ID: 50cd474ac607
Revises: 7ec756420a10
Create Date: 2020-08-21 12:02:26.115630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50cd474ac607'
down_revision = '7ec756420a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assignment_schedule_table_ibfk_2', 'assignment_schedule_table', type_='foreignkey')
    op.drop_constraint('assignment_schedule_table_ibfk_1', 'assignment_schedule_table', type_='foreignkey')
    op.create_foreign_key(None, 'assignment_schedule_table', 'schedule', ['schedule_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'assignment_schedule_table', 'assignment', ['assignment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('resource_schedule_table_ibfk_1', 'resource_schedule_table', type_='foreignkey')
    op.drop_constraint('resource_schedule_table_ibfk_2', 'resource_schedule_table', type_='foreignkey')
    op.create_foreign_key(None, 'resource_schedule_table', 'schedule', ['schedule_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'resource_schedule_table', 'course_resource', ['resource_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource_schedule_table', type_='foreignkey')
    op.drop_constraint(None, 'resource_schedule_table', type_='foreignkey')
    op.create_foreign_key('resource_schedule_table_ibfk_2', 'resource_schedule_table', 'schedule', ['schedule_id'], ['id'])
    op.create_foreign_key('resource_schedule_table_ibfk_1', 'resource_schedule_table', 'course_resource', ['resource_id'], ['id'])
    op.drop_constraint(None, 'assignment_schedule_table', type_='foreignkey')
    op.drop_constraint(None, 'assignment_schedule_table', type_='foreignkey')
    op.create_foreign_key('assignment_schedule_table_ibfk_1', 'assignment_schedule_table', 'assignment', ['assignment_id'], ['id'])
    op.create_foreign_key('assignment_schedule_table_ibfk_2', 'assignment_schedule_table', 'schedule', ['schedule_id'], ['id'])
    # ### end Alembic commands ###
