"""empty message

Revision ID: 774464844358
Revises: a9be4322c9a5
Create Date: 2020-08-19 01:19:34.105286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '774464844358'
down_revision = 'a9be4322c9a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_resource', sa.Column('description', sa.String(length=127), nullable=True))
    op.add_column('course_resource', sa.Column('file', sa.String(length=127), nullable=True))
    op.add_column('course_resource', sa.Column('filename', sa.String(length=127), nullable=True))
    op.drop_constraint('course_resource_ibfk_1', 'course_resource', type_='foreignkey')
    op.drop_column('course_resource', 'data')
    op.drop_column('course_resource', 'course_id')
    op.drop_column('course_resource', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_resource', sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))
    op.add_column('course_resource', sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('course_resource', sa.Column('data', sa.BLOB(), nullable=True))
    op.create_foreign_key('course_resource_ibfk_1', 'course_resource', 'course', ['course_id'], ['cid'])
    op.drop_column('course_resource', 'filename')
    op.drop_column('course_resource', 'file')
    op.drop_column('course_resource', 'description')
    # ### end Alembic commands ###
