"""empty message

Revision ID: 7ec756420a10
Revises: 413003d967c5
Create Date: 2020-08-20 01:21:24.111368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec756420a10'
down_revision = '413003d967c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('datetime', sa.String(length=63), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'datetime')
    # ### end Alembic commands ###
