"""empty message

Revision ID: a51e41e314e0
Revises: 5351db0ecac9
Create Date: 2020-08-20 00:31:54.649064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51e41e314e0'
down_revision = '5351db0ecac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('file', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'file')
    # ### end Alembic commands ###
