"""empty message

Revision ID: a9be4322c9a5
Revises: 214fdd57802b
Create Date: 2020-08-13 17:43:13.067926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9be4322c9a5'
down_revision = '214fdd57802b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('series', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'series')
    # ### end Alembic commands ###
