"""empty message

Revision ID: b2a05e487f56
Revises: 
Create Date: 2020-08-28 01:08:47.161451

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b2a05e487f56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('cid', sa.Integer(), nullable=False),
                    sa.Column('name_zh', sa.String(length=40), nullable=False),
                    sa.Column('name_en', sa.String(length=40), nullable=False),
                    sa.Column('intro', sa.String(length=200), nullable=True),
                    sa.Column('pre_course', sa.String(length=50), nullable=True),
                    sa.Column('textbooks', sa.String(length=50), nullable=True),
                    sa.Column('semester', sa.String(length=50), nullable=True),
                    sa.Column('series', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('cid')
                    )
    op.create_table('tag',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('user',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('gid', sa.String(length=10), nullable=False),
                    sa.Column('email', sa.String(length=24), nullable=False),
                    sa.Column('nickname', sa.String(length=24), nullable=True),
                    sa.Column('auth', sa.SmallInteger(), nullable=True),
                    sa.Column('name', sa.String(length=24), nullable=True),
                    sa.Column('phone', sa.String(length=24), nullable=True),
                    sa.Column('school', sa.String(length=63), nullable=True),
                    sa.PrimaryKeyConstraint('gid'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('nickname')
                    )
    op.create_table('announce',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('course_cid', sa.Integer(), nullable=True),
                    sa.Column('author_gid', sa.String(length=10), nullable=True),
                    sa.Column('title', sa.String(length=63), nullable=True),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['author_gid'], ['user.gid'], ),
                    sa.ForeignKeyConstraint(['course_cid'], ['course.cid'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('answer',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.String(length=500), nullable=False),
                    sa.Column('author_gid', sa.String(length=10), nullable=True),
                    sa.ForeignKeyConstraint(['author_gid'], ['user.gid'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('assignment',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=63), nullable=True),
                    sa.Column('ddl', sa.String(length=63), nullable=True),
                    sa.Column('course_cid', sa.Integer(), nullable=True),
                    sa.Column('file', sa.String(length=40), nullable=True),
                    sa.Column('filename', sa.String(length=63), nullable=True),
                    sa.ForeignKeyConstraint(['course_cid'], ['course.cid'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('course_resource',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(length=127), nullable=True),
                    sa.Column('filename', sa.String(length=127), nullable=True),
                    sa.Column('file', sa.String(length=127), nullable=True),
                    sa.Column('course_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['course_id'], ['course.cid'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('enroll',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_gid', sa.String(length=10), nullable=True),
                    sa.Column('course_cid', sa.Integer(), nullable=True),
                    sa.Column('enroll_type', sa.SmallInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['course_cid'], ['course.cid'], ),
                    sa.ForeignKeyConstraint(['user_gid'], ['user.gid'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('history_answer',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.String(length=500), nullable=False),
                    sa.Column('author_gid', sa.String(length=10), nullable=True),
                    sa.ForeignKeyConstraint(['author_gid'], ['user.gid'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('history_question',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=127), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('author_gid', sa.String(length=10), nullable=True),
                    sa.ForeignKeyConstraint(['author_gid'], ['user.gid'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('photo',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('filename', sa.String(length=127), nullable=True),
                    sa.Column('author_gid', sa.String(length=10), nullable=True),
                    sa.Column('file', sa.String(length=127), nullable=True),
                    sa.ForeignKeyConstraint(['author_gid'], ['user.gid'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('schedule',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('course_id', sa.Integer(), nullable=True),
                    sa.Column('week', sa.Integer(), nullable=True),
                    sa.Column('topic', sa.String(length=255), nullable=True),
                    sa.Column('reference', sa.String(length=255), nullable=True),
                    sa.Column('additional_info', sa.String(length=255), nullable=True),
                    sa.Column('datetime', sa.String(length=63), nullable=True),
                    sa.ForeignKeyConstraint(['course_id'], ['course.cid'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('assignment_schedule_table',
                    sa.Column('assignment_id', sa.Integer(), nullable=True),
                    sa.Column('schedule_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ondelete='CASCADE')
                    )
    op.create_table('question',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=127), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('author_gid', sa.String(length=10), nullable=True),
                    sa.Column('teacher_aid', sa.Integer(), nullable=True),
                    sa.Column('student_aid', sa.Integer(), nullable=True),
                    sa.Column('course_id', sa.Integer(), nullable=True),
                    sa.Column('update_time', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['author_gid'], ['user.gid'], ),
                    sa.ForeignKeyConstraint(['course_id'], ['course.cid'], ),
                    sa.ForeignKeyConstraint(['student_aid'], ['answer.id'], ),
                    sa.ForeignKeyConstraint(['teacher_aid'], ['answer.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('resource_schedule_table',
                    sa.Column('resource_id', sa.Integer(), nullable=True),
                    sa.Column('schedule_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['resource_id'], ['course_resource.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ondelete='CASCADE')
                    )
    op.create_table('discussion_topic',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('question_id', sa.Integer(), nullable=True),
                    sa.Column('title', sa.String(length=127), nullable=False),
                    sa.Column('content', sa.String(length=500), nullable=False),
                    sa.Column('author_gid', sa.String(length=10), nullable=True),
                    sa.Column('stars', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['author_gid'], ['user.gid'], ),
                    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('history',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('root_qid', sa.Integer(), nullable=True),
                    sa.Column('qid', sa.Integer(), nullable=True),
                    sa.Column('student_aid', sa.Integer(), nullable=True),
                    sa.Column('teacher_aid', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['qid'], ['history_question.id'], ),
                    sa.ForeignKeyConstraint(['root_qid'], ['question.id'], ),
                    sa.ForeignKeyConstraint(['student_aid'], ['history_answer.id'], ),
                    sa.ForeignKeyConstraint(['teacher_aid'], ['history_answer.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('question_tag_table',
                    sa.Column('tag_id', sa.Integer(), nullable=True),
                    sa.Column('question_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
                    )
    op.create_table('question_up_vote',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('question_id', sa.Integer(), nullable=True),
                    sa.Column('user_gid', sa.String(length=10), nullable=True),
                    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
                    sa.ForeignKeyConstraint(['user_gid'], ['user.gid'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('discussion_answer',
                    sa.Column('create_time', sa.Integer(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('topic_id', sa.Integer(), nullable=True),
                    sa.Column('content', sa.String(length=500), nullable=False),
                    sa.Column('author_gid', sa.String(length=10), nullable=True),
                    sa.Column('reply_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['author_gid'], ['user.gid'], ),
                    sa.ForeignKeyConstraint(['topic_id'], ['discussion_topic.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discussion_answer')
    op.drop_table('question_up_vote')
    op.drop_table('question_tag_table')
    op.drop_table('history')
    op.drop_table('discussion_topic')
    op.drop_table('resource_schedule_table')
    op.drop_table('question')
    op.drop_table('assignment_schedule_table')
    op.drop_table('schedule')
    op.drop_table('photo')
    op.drop_table('history_question')
    op.drop_table('history_answer')
    op.drop_table('enroll')
    op.drop_table('course_resource')
    op.drop_table('assignment')
    op.drop_table('answer')
    op.drop_table('announce')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('course')
    # ### end Alembic commands ###
