"""empty message

Revision ID: f534cc5cab3f
Revises: 
Create Date: 2020-08-12 15:58:52.275137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f534cc5cab3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=24), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=24), nullable=True))
    op.add_column('user', sa.Column('school', sa.String(length=63), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'school')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
