"""empty message

Revision ID: fa5f0f473905
Revises: 0a8c7ec878a5
Create Date: 2020-08-23 01:51:41.720277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa5f0f473905'
down_revision = '0a8c7ec878a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('additional_info', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'additional_info')
    # ### end Alembic commands ###
