"""empty message

Revision ID: ffe3f323e216
Revises: 774464844358
Create Date: 2020-08-19 01:22:59.589627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe3f323e216'
down_revision = '774464844358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_resource', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_resource', 'course', ['course_id'], ['cid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_resource', type_='foreignkey')
    op.drop_column('course_resource', 'course_id')
    # ### end Alembic commands ###
